// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnkXIm4vbupybyXXk29QGASlnwWhq_ZVg',
    appId: '1:229129838603:web:20484195da01e75037270e',
    messagingSenderId: '229129838603',
    projectId: 'uploading-files-99',
    authDomain: 'uploading-files-99.firebaseapp.com',
    storageBucket: 'uploading-files-99.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBta8dNY1gDztzyYDuXPdlS6qAcNAxsznw',
    appId: '1:229129838603:android:f8315c4287529eaa37270e',
    messagingSenderId: '229129838603',
    projectId: 'uploading-files-99',
    storageBucket: 'uploading-files-99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ4m8YN_GGi5Vx9bZNM5cJA22z47O5TPE',
    appId: '1:229129838603:ios:83a45c77dac87bc937270e',
    messagingSenderId: '229129838603',
    projectId: 'uploading-files-99',
    storageBucket: 'uploading-files-99.appspot.com',
    iosClientId: '229129838603-d0rp1tpkhbuo6ft7vhqgoturgh1fnrn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fileUpload',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ4m8YN_GGi5Vx9bZNM5cJA22z47O5TPE',
    appId: '1:229129838603:ios:83a45c77dac87bc937270e',
    messagingSenderId: '229129838603',
    projectId: 'uploading-files-99',
    storageBucket: 'uploading-files-99.appspot.com',
    iosClientId: '229129838603-d0rp1tpkhbuo6ft7vhqgoturgh1fnrn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fileUpload',
  );
}
